replicaCount: 2
image:
  tag: latest
service:
  nodePort: 30081
rollout:
  strategy: canary
  steps:
    - setWeight: 25
    - pause: {duration: 15s}
    - setWeight: 50
    - pause: {duration: 15s}
    - setWeight: 100    
