apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-myapp
namePrefix: prod-

helmCharts:
  - name: myapp
    releaseName: myapp
    chartPath: ../../helm/myapp
    valuesFiles:
      - values-prod.yaml
    includeCRDs: false
